name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: 'pubspec.yaml'

      - name: Create Keystore and Properties Files
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks
          # FIX: All lines below now correctly point to the android/app/ directory
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
          echo "storeFile=release-keystore.jks" >> android/app/key.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/*.apk
          asset_name: Paperwise-v${{ github.ref_name }}-${{ basename(github.event.release.tag_name) }}.apk # Adjust if you want more specific naming
          tag: ${{ github.ref }}
          overwrite: true
